version: '3.8'
services: 
  mongo:
    image: mongo:latest
    env_file:
    - ./mongoDB/.env
    ports:
      - 27017:27017
    volumes:
      - prod_data:/data/db
volumes:
  prod_data:
    driver: local
