version: '3.8'
services: 
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: samiam
      MONGO_INITDB_ROOT_PASSWORD: idonotlike
    ports:
      - 27017:27017
    volumes:
      - prod_data:/data/db
volumes:
  prod_data:
    driver: local
