version: '3.8'
services:
  mongo:
    image: mongo:8.0.0-rc4-jammy
    env_file:
      - ./mongoDB/.env
    ports:
      - 27017:27017
    volumes:
      - prod_data:/data/db

  redis:
    environment:
      SENTINEL: 'false'
      STANDALONE: 'false'
    build:
      context: ./redis
      args:
        redis_version: '7.0.10'
    hostname: server
    ports:
      - '7000-7050:7000-7050'

  user_management:
    depends_on:
      - mongo
    build: ./user_management
    environment:
      - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_HOST=mongo
      - SPRING_DATA_MONGODB_URI=mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@mongo:27017/${MONGO_DB_NAME}?authSource=admin
    ports:
      - 8080:8080
volumes:
  prod_data:
    driver: local